### PR TITLE
DDF-1183: Update to include findbugs option.

### PR DESCRIPTION
**Pull request by ghost**
[Review on Reviewable](https://reviewable.io/reviews/codice/ddf-parent/12)

### CODE REVIEW

**Comment by ghost** [comment]
@oconnormi, @jckilmer, @lessarderic

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-parent/12)

**Comment by oconnormi** [comment]
Reviewed files:
- pom.xml @ r3

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-parent/12)

**Comment by lessarderic** [comment]
Reviewed files:
- pom.xml @ r3

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-parent/12)

**Comment by lessarderic** [comment]
Looks good to me. Any idea why the Travis build would be failing here? Is this building fine on your end?

**Comment by jckilmer** [comment]
Reviewed files:
- pom.xml @ r3

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-parent/12)

**Comment by ghost** [comment]
It is failing because it cannot see the updated ddf-support/support-findbugs information.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-parent/12)

**Comment by jckilmer** [comment]
Reviewed files:
- pom.xml @ r4

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-parent/12)

**Comment by ghost** [comment]
@phil, @shaun

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-parent/12)

**Comment by shaundmorris** [comment]
Received the ICLA so should be good to go here.

---

Reviewed files:
- pom.xml @ r4

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-parent/12)

**Pull request merged**
