### PR TITLE
DDF-1241 Build DDF documentation by default

### PR DESCRIPTION
**Pull request by kguerriero**
[Review on Reviewable](https://reviewable.io/reviews/codice/ddf-parent/23)

### CODE REVIEW

**Comment by kguerriero** [comment]
@SmithJosh

**Comment by pklinef** [comment]
:+1:

**Comment by shaundmorris** [comment]
:+1: We should make sure to post on the developer group the change (to have it active by default) and how to turn off the documentation profile.  Think we had some questions on the change.

---

Review status: :shipit: all files reviewed, all discussions resolved, all commit checks successful.
Reviewed files:
- pom.xml @ r1

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-parent/23)

**Comment by SmithJosh** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[pom.xml, line 695 [r1]](https://reviewable.io:443/reviews/codice/ddf-parent/23#-JrtRZ5Zkw0c3TZigl-Z)** ([raw file](https://github.com/codice/ddf-parent/blob/6e6ed36f6ac023d725fb9fd7c0b51f047612a75a/pom.xml#L695)):</sup>
Setting this profile to be active by default causes it to be run on every project, regardless of whether they actually produce documentation. The build fails for me because the assembly plugin toward the end of the profile looks for a file ${project.basedir}/src/assembly/bin.xml, which doesn't exist for some of the projects (e.g. ddf.distribution.kernel). I suggest replacing the activation element with the following:

```
<activation>
    <file>
        <exists>${basedir}/src/assembly/bin.xml</exists>
    </file>
</activation>
```

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-parent/23)

**Comment by SmithJosh** [comment]
Verified that everything builds successfully, that the documentation profile runs by default and that it is only active for projects with docs folders. The changes should be safe to merge.

**Comment by shaundmorris** [comment]
I verified the build as well.

**Pull request merged**
