### PR TITLE
DDF-1288: removed argLine propetry which was breaking jacoco.

### PR DESCRIPTION
**Pull request by djblue**
@lessarderic @andrewkfiedler please review. 

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf-parent/26)

### CODE REVIEW

**Comment by lessarderic** [comment]
Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-parent/26)

**Comment by kguerriero** [comment]
All unit tests and integration tests pass.

**Comment by andrewkfiedler** [comment]
@andrew-fiedler

**Comment by andrewkfiedler** [comment]
I'm having trouble getting the other repo's to run jacoco. 

```
Skipping JaCoCo execution due to missing execution data file:/Users/andrewfiedler/ddf/ddf-admin/admin-app/target/jacoco.exec
```

**Comment by lessarderic** [comment]
@andrew-fiedler: Can you do a mvn help:effective-pom in one of the projects where you expect jacoco to run and make sure you don't see the <argLine> property anymore?

**Comment by andrewkfiedler** [comment]
I went to go reproduce it today, but couldn't.  

:+1: built and tested

**Comment by shaundmorris** [comment]
Ran build and integration tests successfully.

**Pull request merged**
