### PR TITLE
DDF-1241 Build DDF documentation by default

### PR DESCRIPTION
**Pull request by kguerriero**
[Review on Reviewable](https://reviewable.io/reviews/codice/ddf-parent/21)

### CODE REVIEW

**Comment by mrmateo** [comment]
Couple questions:
1) Is that an accurate ticket number? I'm not seeing a ticket for DDF-2666 on the Codice JIRA at all.
2) This seems contrary to https://tools.codice.org/jira/browse/DDF-1103. Has something changed since that ticket was completed?

**Comment by kguerriero** [comment]
Updated ticket information, should be DDF-1241, thanks.
Yes, the lack of documentation being generated was causing confusion. It's possible to disable the generation using 
mvn clean install -P!release

@shaundmorris @pklinef

**Comment by pklinef** [comment]
Review status: 0 of 1 files reviewed, 1 unresolved discussion, all commit checks successful.

---

<sup>**[pom.xml, line 693 [r1]](https://reviewable.io:443/reviews/codice/ddf-parent/21#-JrYG6kU6TiIX9xMPfRw)** ([raw file](https://github.com/codice/ddf-parent/blob/c7e7d7fb677e26bc95e893800a446a39bf9baa43/pom.xml#L693)):</sup>
Change the profile id from release to documentation.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-parent/21)

**Comment by pklinef** [comment]
@mrmateo Good Enabling documentation as part of the build is needed for DDF-1249 so it can be included in the distribution zip.  Since it is in a profile, it can be disabled if needed.  I updated DDF-1241 to link to DDF-1249 and I added documentation in the distribution zip to the roadmap.

**Comment by mrmateo** [comment]
@pklinef - yeah, my confusion was that I thought that was already done as part of DDF-1103 when @shaundmorris  added the release profile and was asked (on google groups) to update the release documentation to make note that you had to perform the release with the release profile.

**Comment by shaundmorris** [comment]
@mrmateo that makes sense on the confusion. After actually going through the release process I found documenting another flag at that moment can lead to it being error prone (easily forgotten or fat-fingered). I also reposted with the latest information: https://groups.google.com/forum/?fromgroups=#!searchin/ddf-developers/profile/ddf-developers/DNA2-s7g3VE/BSUvh6q_2w4J

**Pull request closed without merging**
