### PR TITLE
DDF-1226 Moved support-pmd project to ddf-support

### PR DESCRIPTION
**Pull request by jckilmer**
[Review on Reviewable](https://reviewable.io/reviews/codice/ddf-parent/28)

### CODE REVIEW

**Comment by jckilmer** [comment]
Reviewers: @shaundmorris @lessarderic @andrew-fiedler

**Comment by lessarderic** [comment]
We're getting the following PMD warning when building:

```
[INFO] --- maven-pmd-plugin:3.4:pmd (pmd) @ catalog-solr-external-provider ---
[WARNING] Unable to locate Source XRef to link to - DISABLED
```

Can you add the following to the pmd section of the ddf-parent pom file and see if it solves the problem?

``` xml
<reporting>
    <plugins>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-jxr-plugin</artifactId>
            <version>2.3</version>
        </plugin>
    </plugins>
</reporting>
```

Link to stackoverflow on this: http://stackoverflow.com/questions/12038238/unable-to-locate-source-xref-to-link-to

**Comment by lessarderic** [comment]
Did a clean build of ddf-support, ddf-parent and ddf-catalog and everything looks good.

:+1:

**Comment by lessarderic** [comment]
Tried to above fix to get rid of the warning and didn't work so let's just ignore that for now and move on.

**Comment by shaundmorris** [comment]
:+1: we wanted to move support into platform, which looks like we can do from a build stand point, but there are issues with the maven release plugin when you attempt to release. This will at least allow for releasing ddf-parent to be smooth.

**Comment by shaundmorris** [comment]
Verified build

**Pull request merged**
